### ISSUE TITLE
Quickstart guide

### ISSUE THREAD

**Issue by michaeloliverx** [dmontagu/backend-skeleton#1]
Hi,
This repo interests me as I found the official full-stack version quite daunting.  This seems much more organized.  Is there a quick-start guide that goes over the environment ?
Thanks!

**Comment by dmontagu** [comment]
No quick-start guide just yet but I am happy to put one together. Any specific requests? I’ll try to at least flesh out the README.md tomorrow.

**Comment by michaeloliverx** [comment]
Not anything in particular. A basic overview of the stack and any decisions you have made to be aware off?
